spring:
  cloud:
    stream:
      kafka:
        binder:
          configuration:
            commit:
              interval:
                mms: 1000
            default:
              key:
                serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              value:
                serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        users_in:
          consumer:
            application-id: consumer-users
          destination: users